openapi: 3.0.0
info:
  title: Longhorn Monitor
  version: 0.1.0
  contact:
    email: kontakt@der-fetzer.de
paths:
  /podHealth:
    get:
      operationId: getHealth
      summary: Get pod health status entries
      responses:
        '200':
          description: A list of pod health entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PodHealth'
        '400':
          description: Bad Request
    post:
      operationId: postHealth
      summary: Update pod health status entry
      parameters:
        - name: isHealthy
          in: query
          required: true
          schema:
            type: boolean
          description: Is the pod healthy?
        - name: podName
          in: query
          required: true
          schema:
            type: string
          description: Name of the pod
        - name: namespace
          in: query
          required: true
          schema:
            type: string
          description: Namespace the pod is in
      responses:
        '201':
          description: OK
        '400':
          description: Bad Request
    delete:
      operationId: deleteHealth
      summary: Delete pod health entry
      parameters:
        - name: podName
          in: query
          required: true
          schema:
            type: string
          description: Name of the pod
        - name: namespace
          in: query
          required: true
          schema:
            type: string
          description: Namespace the pod is in
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not found
security: []
servers: []
components:
  links: {}
  callbacks: {}
  schemas:
    PodHealth:
      type: object
      required:
        - podName
        - namespace
        - isHealthy
        - errorCount
        - isDeleted
      properties:
        podName:
          type: string
        namespace:
          type: string
        isHealthy:
          type: boolean
        isDeleted:
          type: boolean
        errorCount:
          type: integer
          format: int32
